import type { Command } from '../commands.js';

export const onboardingCommand: Command = {
  name: 'onboarding',
  description: 'First-run setup and introduction',
  isEnabled: () => true,
  call: async (args, context) => {
    const lines = context.language === 'zh-CN' ? [
      '\u{1F44B} 欢迎使用 MiMo Code！',
      '',
      'MiMo Code 是一个终端 AI 编程助手，可以帮助你：',
      '  • 编写和修改代码',
      '  • 执行命令和脚本',
      '  • 搜索文件和内容',
      '  • 管理任务和项目',
      '',
      '快速开始：',
      '  1. 输入问题或任务，MiMo 会自动执行',
      '  2. 按 Tab 查看常用命令',
      '  3. 输入 /help 查看所有命令',
      '  4. 输入 /language 切换语言',
      '',
      '配置 API：',
      '  /config set apiKey <your-key>',
      '  /config set baseUrl <api-url>',
      '',
      '开始吧！输入任何内容开始对话。',
    ] : context.language === 'ja' ? [
      '\u{1F44B} MiMo Code へようこそ！',
      '',
      'MiMo Code はターミナル AI コーディングアシスタントです：',
      '  • コードの作成と修正',
      '  • コマンドとスクリプトの実行',
      '  • ファイルとコンテンツの検索',
      '  • タスクとプロジェクトの管理',
      '',
      'クイックスタート：',
      '  1. 質問やタスクを入力すると、MiMo が自動的に実行します',
      '  2. Tab でよく使うコマンドを表示',
      '  3. /help ですべてのコマンドを表示',
      '  4. /language で言語を切り替え',
      '',
      'API を設定：',
      '  /config set apiKey <your-key>',
      '  /config set baseUrl <api-url>',
      '',
      '始めましょう！何か入力して会話を始めてください。',
    ] : [
      '\u{1F44B} Welcome to MiMo Code!',
      '',
      'MiMo Code is a terminal AI coding assistant that can:',
      '  • Write and modify code',
      '  • Execute commands and scripts',
      '  • Search files and content',
      '  • Manage tasks and projects',
      '',
      'Quick start:',
      '  1. Type a question or task, MiMo will execute it automatically',
      '  2. Press Tab to see common commands',
      '  3. Type /help to see all commands',
      '  4. Type /language to switch languages',
      '',
      'Configure API:',
      '  /config set apiKey <your-key>',
      '  /config set baseUrl <api-url>',
      '',
      'Let\'s go! Type anything to start a conversation.',
    ];
    return lines.join('\n');
  },
};
